# sparkiy client-w10
# AppVeyor project configuration file
-
  version: 2.0.{build}
  os: Visual Studio 2015
  configuration: Debug
  platform: x86

  clone_folder: c:\repo
  
  before_build:
    - SET PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
    - nuget restore sparkiy\sparkiy.sln
  
  build:
    project: sparkiy\sparkiy.sln
    parallel: true

  notifications:
    - provider: Webhook
      url: https://webhooks.gitter.im/e/fc3c63967ea87299f8ea
